In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.8.0+cu126


## Intro to Tensors

PyTorch tensors are created using 'torch.Tensor()'

In [34]:
# Create a tensor using torch.tensor(), can use dtype to specify datatype, can specify that data is stored on gpu which runs faster
scalar = torch.tensor(190)
print(scalar)

vector = torch.tensor([19,5])
print(vector)

matrix = torch.tensor([[1.,2.],
                      [3.,4.]], dtype=torch.float16)
print(matrix)

tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [1,7,9]]], dtype=torch.int32)
print(tensor)

tensor(190)
tensor([19,  5])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
tensor([[[1, 2, 3],
         [3, 6, 9],
         [1, 7, 9]]], dtype=torch.int32)


In [35]:
# Can figure out dimensions using torch.tensor.ndim and shape using torch.tensor.shape
print(scalar.ndim)
print(scalar.shape)

print(tensor.ndim)
print(tensor.shape)

0
torch.Size([])
3
torch.Size([1, 3, 3])


In [38]:
# Get tensor back as python object using torch.tensor.item() --> only works on scalar
print(scalar.item())

190
