<a href="https://colab.research.google.com/github/james-yu2005/pytorch-practice/blob/main/pytorch_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.8.0+cu126


## Intro to Tensors

PyTorch tensors are created using 'torch.Tensor()'

Matrix and Tensors are often uppercase while vectors and scalars are lowercase

In [2]:
# Create a tensor using torch.tensor(), can use dtype to specify datatype, can specify that data is stored on gpu which runs faster
scalar = torch.tensor(190)
print(scalar)

vector = torch.tensor([19,5])
print(vector)

matrix = torch.tensor([[1.,2.],
                      [3.,4.]], dtype=torch.float16)
print(matrix)

tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [1,7,9]]], dtype=torch.int32)
print(tensor)

tensor(190)
tensor([19,  5])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
tensor([[[1, 2, 3],
         [3, 6, 9],
         [1, 7, 9]]], dtype=torch.int32)


In [3]:
# Can figure out dimensions using torch.tensor.ndim and shape using torch.tensor.shape
print(scalar.ndim)
print(scalar.shape)

print(tensor.ndim)
print(tensor.shape)

0
torch.Size([])
3
torch.Size([1, 3, 3])


In [4]:
# Get tensor back as python object using torch.tensor.item() --> only works on scalar
print(scalar.item())

190


## Random Tensors

Neural networks learn start with tensors with random numbers and adjust based on the data to better represent them as the model gets trained

In [5]:
# Random tensor of size (3,4)

rand_tensor = torch.rand(3,4, dtype=torch.float16)
rand_tensor

tensor([[0.5581, 0.2588, 0.4033, 0.1157],
        [0.8672, 0.9683, 0.9087, 0.2441],
        [0.2393, 0.5239, 0.9722, 0.7202]], dtype=torch.float16)

In [6]:
print(rand_tensor.ndim)
print(rand_tensor.shape)

2
torch.Size([3, 4])


In [7]:
image_size_tensor = torch.rand(size=(224,224,3))
image_size_tensor.shape

torch.Size([224, 224, 3])

## Zeros and Ones

In [8]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Note that this is Hadamard Product and not matrix multiplication

zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
# Default is torch.float32
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [12]:
# torch.range()
torch_range = torch.arange(0,10,1)
torch_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Creating tensors like
ten_zeros = torch.zeros_like(torch_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [14]:
float_32_tensor = torch.tensor([[1,2],[3,4]],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([[1., 2.],
        [3., 4.]])

In [15]:
float_16_tensor = torch.tensor([[5,6],[7,8]],
                               dtype=torch.float16)

In [16]:
float_16_tensor * float_32_tensor

tensor([[ 5., 12.],
        [21., 32.]])

In [17]:
# Can change datatype using torch.type()
float_16_tensor.type(torch.float64)

tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)

## Manipulating tensors

- addition
- subtraction
- multiplication (Hadamard product)
- division
- matrix multiplication


In [18]:
# Create a tensor
tensor = torch.tensor([1,2,3,4])
print(tensor + 10)
print(torch.add(tensor,10))

tensor([11, 12, 13, 14])
tensor([11, 12, 13, 14])


In [19]:
# Multiply tensor by 10
print(tensor * 10)
print(torch.mul(tensor,10))

tensor([10, 20, 30, 40])
tensor([10, 20, 30, 40])


In [20]:
# Subtract tensor by 10
print(tensor - 10)
print(torch.sub(tensor,10))

tensor([-9, -8, -7, -6])
tensor([-9, -8, -7, -6])


In [21]:
# Divide tensor by 10
print(tensor/2)
print(torch.div(tensor,2))

tensor([0.5000, 1.0000, 1.5000, 2.0000])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


## Multiplication

- element-wise (Hadamard Product)
- matrix multiplication (Dot Product if 1D vector)

In [22]:
tensor1 = torch.arange(0,5,2)
tensor2 = torch.arange(0,5,2)

print(tensor1)
print(tensor2)

tensor([0, 2, 4])
tensor([0, 2, 4])


In [23]:
# Element wise
tensor1 * tensor2

tensor([ 0,  4, 16])

In [24]:
# Matrix multiplication
%%time
tensor3 = torch.matmul(tensor1,tensor2)
tensor3

CPU times: user 0 ns, sys: 709 µs, total: 709 µs
Wall time: 13.5 ms


tensor(20)

In [25]:
# Higher shape matrix multiplication
t1 = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

t2 = torch.tensor([[7,8],
                 [9,10],
                 [11,12]])
t2 = t2.T
print(t2)
torch.matmul(t1,t2)

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Tensor Aggregation

In [26]:
x = torch.arange(0,100,10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [27]:
x.max(), x.min()

(tensor(90.), tensor(0.))

In [28]:
# torch.mean requires float32 to work
torch.mean(x)

tensor(45.)

In [29]:
# Find the sum
x.sum()

tensor(450.)

## Find the positional min and max

In [30]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [31]:
# Find the position of tensor with min value
x.argmin()

tensor(0)

In [32]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, unsqueezing tensors

In [33]:
# Make a tensor
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [34]:
# Add an extra dimension
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [35]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [36]:
# Changing z changes x (view of a tensor shares same memeory as original)
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [37]:
# Stack tensors on top of each other using torch.stack
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [38]:
# torch.squeeze() - remove all 1 dimensions
x = torch.rand(1,3,4,1)
print(x,x.shape)
x_squeeze = x.squeeze()
print(x_squeeze,x_squeeze.shape)

tensor([[[[0.1233],
          [0.9771],
          [0.9512],
          [0.5082]],

         [[0.4637],
          [0.3530],
          [0.5467],
          [0.0827]],

         [[0.2614],
          [0.4426],
          [0.6878],
          [0.2833]]]]) torch.Size([1, 3, 4, 1])
tensor([[0.1233, 0.9771, 0.9512, 0.5082],
        [0.4637, 0.3530, 0.5467, 0.0827],
        [0.2614, 0.4426, 0.6878, 0.2833]]) torch.Size([3, 4])


In [39]:
# torch.unsqueeze() - add dimension of 1, dim = index of added 1 dimension
x_unsqueeze = x_squeeze.unsqueeze(dim=2)
x_unsqueeze.shape, x_unsqueeze

(torch.Size([3, 4, 1]),
 tensor([[[0.1233],
          [0.9771],
          [0.9512],
          [0.5082]],
 
         [[0.4637],
          [0.3530],
          [0.5467],
          [0.0827]],
 
         [[0.2614],
          [0.4426],
          [0.6878],
          [0.2833]]]))

In [40]:
# torch.permute() - change the order of parameters, feed in array, then desired index
x_orig = torch.rand(224,224,3)
print(x_orig.shape)

# rearrange the axes
x_permute = x_orig.permute(2,0,1)
print(x_permute.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [41]:
# permute shares same view as orig
x_orig[0,0,0] = 999
x_orig[0,0,0],x_permute[0,0,0]

(tensor(999.), tensor(999.))

##Indexing with Pytorch

In [42]:
x = torch.arange(1,11).reshape(1,2,5)
x

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])

In [45]:
# commas depend on the shape of your tensor, it goes by dimension in order
# from 0th dimension to (n-1)th dimension where n is len(tensor)
x[:,1,0:2]

tensor([[6, 7]])

In [46]:
# if doing x[0][0][0], could also do x[0,0,0]
x[0][0][0],x[0,0,0]

(tensor(1), tensor(1))

## PyTorch tensors & NumPy

NumPy is used for numerical computations,
can convert from numpy to torch and vice versa

In [58]:
# NumPy array to tensor, numpy default is float64 while torch is float32
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [59]:
tensor.dtype

torch.float32

In [60]:
# new tensor in memory when using from_numpy
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [61]:
# Tensor to NumPy array
tensor = torch.zeros(9,4)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32))

In [63]:
# new numpy array also has new memory
tensor = tensor + 1
tensor,numpy_tensor

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

## Reproducability (trying to take random out of random)


In [70]:
t1 = torch.rand(3,3)
t2 = torch.rand(3,3)
t1,t2

(tensor([[0.3946, 0.4742, 0.7651],
         [0.4885, 0.2533, 0.0493],
         [0.8784, 0.1922, 0.9254]]),
 tensor([[0.9261, 0.4325, 0.7545],
         [0.1540, 0.2870, 0.9908],
         [0.6460, 0.6271, 0.7494]]))

In [72]:
# Set random seed
RAND_SEED = 42
torch.manual_seed(RAND_SEED)
t1 = torch.rand(3,3)

torch.manual_seed(RAND_SEED)
t2 = torch.rand(3,3)
t1,t2

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))

## Running tensors and PyTorch objects on GPU
gpu makes computational calculations faster using CUDA and NVIDIA hardware and pytorch behind the scenes

/bin/bash: line 1: nvidia-smi: command not found
