<a href="https://colab.research.google.com/github/james-yu2005/pytorch-practice/blob/main/pytorch_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.8.0+cu126


## Intro to Tensors

PyTorch tensors are created using 'torch.Tensor()'

Matrix and Tensors are often uppercase while vectors and scalars are lowercase

In [4]:
# Create a tensor using torch.tensor(), can use dtype to specify datatype, can specify that data is stored on gpu which runs faster
scalar = torch.tensor(190)
print(scalar)

vector = torch.tensor([19,5])
print(vector)

matrix = torch.tensor([[1.,2.],
                      [3.,4.]], dtype=torch.float16)
print(matrix)

tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [1,7,9]]], dtype=torch.int32)
print(tensor)

tensor(190)
tensor([19,  5])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
tensor([[[1, 2, 3],
         [3, 6, 9],
         [1, 7, 9]]], dtype=torch.int32)


In [5]:
# Can figure out dimensions using torch.tensor.ndim and shape using torch.tensor.shape
print(scalar.ndim)
print(scalar.shape)

print(tensor.ndim)
print(tensor.shape)

0
torch.Size([])
3
torch.Size([1, 3, 3])


In [6]:
# Get tensor back as python object using torch.tensor.item() --> only works on scalar
print(scalar.item())

190


## Random Tensors

Neural networks learn start with tensors with random numbers and adjust based on the data to better represent them as the model gets trained

In [7]:
# Random tensor of size (3,4)

rand_tensor = torch.rand(3,4, dtype=torch.float16)
rand_tensor

tensor([[0.3301, 0.1865, 0.3501, 0.2646],
        [0.1885, 0.5649, 0.5552, 0.8916],
        [0.0361, 0.3008, 0.3789, 0.9507]], dtype=torch.float16)

In [8]:
print(rand_tensor.ndim)
print(rand_tensor.shape)

2
torch.Size([3, 4])


In [9]:
image_size_tensor = torch.rand(size=(224,224,3))
image_size_tensor.shape

torch.Size([224, 224, 3])

## Zeros and Ones

In [10]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# Note that this is Hadamard Product and not matrix multiplication

zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
# Default is torch.float32
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [19]:
# torch.range()
torch_range = torch.arange(0,10,1)
torch_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Creating tensors like
ten_zeros = torch.zeros_like(torch_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [37]:
float_32_tensor = torch.tensor([[1,2],[3,4]],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([[1., 2.],
        [3., 4.]])

In [38]:
float_16_tensor = torch.tensor([[5,6],[7,8]],
                               dtype=torch.float16)

In [39]:
float_16_tensor * float_32_tensor

tensor([[ 5., 12.],
        [21., 32.]])

In [34]:
# Can change datatype using torch.type()
float_16_tensor.type(torch.float64)

tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)

## Manipulating tensors

- addition
- subtraction
- multiplication (Hadamard product)
- division
- matrix multiplication


In [46]:
# Create a tensor
tensor = torch.tensor([1,2,3,4])
print(tensor + 10)
print(torch.add(tensor,10))

tensor([11, 12, 13, 14])
tensor([11, 12, 13, 14])


In [45]:
# Multiply tensor by 10
print(tensor * 10)
print(torch.mul(tensor,10))

tensor([10, 20, 30, 40])
tensor([10, 20, 30, 40])


In [47]:
# Subtract tensor by 10
print(tensor - 10)
print(torch.sub(tensor,10))

tensor([-9, -8, -7, -6])
tensor([-9, -8, -7, -6])


In [48]:
# Divide tensor by 10
print(tensor/2)
print(torch.div(tensor,2))

tensor([0.5000, 1.0000, 1.5000, 2.0000])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


## Multiplication

- element-wise (Hadamard Product)
- matrix multiplication (Dot Product if 1D vector)

In [51]:
tensor1 = torch.arange(0,5,2)
tensor2 = torch.arange(0,5,2)

print(tensor1)
print(tensor2)

tensor([0, 2, 4])
tensor([0, 2, 4])


In [52]:
# Element wise
tensor1 * tensor2

tensor([ 0,  4, 16])

In [54]:
# Matrix multiplication
%%time
tensor3 = torch.matmul(tensor1,tensor2)
tensor3

CPU times: user 153 µs, sys: 5 µs, total: 158 µs
Wall time: 165 µs


tensor(20)

In [61]:
# Higher shape matrix multiplication
t1 = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

t2 = torch.tensor([[7,8],
                 [9,10],
                 [11,12]])
t2 = t2.T
print(t2)
torch.matmul(t1,t2)

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])