<a href="https://colab.research.google.com/github/james-yu2005/pytorch-practice/blob/main/pytorch_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.8.0+cu126


## Intro to Tensors

PyTorch tensors are created using 'torch.Tensor()'

Matrix and Tensors are often uppercase while vectors and scalars are lowercase

In [ ]:
# Create a tensor using torch.tensor(), can use dtype to specify datatype, can specify that data is stored on gpu which runs faster
scalar = torch.tensor(190)
print(scalar)

vector = torch.tensor([19,5])
print(vector)

matrix = torch.tensor([[1.,2.],
                      [3.,4.]], dtype=torch.float16)
print(matrix)

tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [1,7,9]]], dtype=torch.int32)
print(tensor)

tensor(190)
tensor([19,  5])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
tensor([[[1, 2, 3],
         [3, 6, 9],
         [1, 7, 9]]], dtype=torch.int32)


In [ ]:
# Can figure out dimensions using torch.tensor.ndim and shape using torch.tensor.shape
print(scalar.ndim)
print(scalar.shape)

print(tensor.ndim)
print(tensor.shape)

0
torch.Size([])
3
torch.Size([1, 3, 3])


In [ ]:
# Get tensor back as python object using torch.tensor.item() --> only works on scalar
print(scalar.item())

190


## Random Tensors

Neural networks learn start with tensors with random numbers and adjust based on the data to better represent them as the model gets trained

In [ ]:
# Random tensor of size (3,4)

rand_tensor = torch.rand(3,4, dtype=torch.float16)
rand_tensor

tensor([[3.6328e-01, 7.4170e-01, 2.4561e-01, 8.5986e-01],
        [7.9150e-01, 7.6318e-01, 5.3809e-01, 1.2305e-01],
        [5.9473e-01, 4.8828e-04, 4.6240e-01, 7.0068e-01]], dtype=torch.float16)

In [ ]:
print(rand_tensor.ndim)
print(rand_tensor.shape)

2
torch.Size([3, 4])


In [ ]:
image_size_tensor = torch.rand(size=(224,224,3))
image_size_tensor.shape

torch.Size([224, 224, 3])

## Zeros and Ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Note that this is Hadamard Product and not matrix multiplication

zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## 1:46:55

https://www.youtube.com/watch?v=V_xro1bcAuA&ab_channel=freeCodeCamp.org